### ISSUE TITLE
Use the CUDA.jl occupancy API

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/LogicCircuits.jl#101]
https://github.com/JuliaGPU/CUDA.jl/blob/4eb99b9f53acfc02a01f92d4a0a2b219bf8994cc/src/indexing.jl#L32-L36

**Comment by guyvdbroeck** [comment]
https://discourse.julialang.org/t/the-most-general-way-to-estimate-the-optimal-arguments-for-cuda-macro/39342

**Comment by khosravipasha** [comment]
Trying it here: 263890a60dab9773e95df8214f5b5f2311f10e22 and https://github.com/Juice-jl/ProbabilisticCircuits.jl/commit/b23055efb6275794350880f8a61b420af5b764af

Queries left to use new balance option
- [x] flow up and down (satisfies)
- [x] marginal (from PCs)
- [ ] map (from PCs)
- [ ] sample (from PCs)
- [ ] gradients (from PCs)
