### ISSUE TITLE
add `respects_vtree`

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/LogicCircuits.jl#27]
Add the ability to verify structured decomposability.

**Comment by khosravipasha** [comment]
Also this is relevant https://github.com/Juice-jl/LogicCircuits.jl/issues/8 (inferring the vtree if not given)

**Comment by guyvdbroeck** [comment]
Added the ability to ask `respects_vtree(circuit,vtree)` and `respects_vtree(struct_circuit)`.
