### ISSUE TITLE
SnoopCompile.jl

### ISSUE THREAD

**Issue by khosravipasha** [Juice-jl/LogicCircuits.jl#34]
See if this can help us precompile our unit tests so that common use cases become already precompiled so they load faster.

https://timholy.github.io/SnoopCompile.jl/stable/

**Comment by khosravipasha** [comment]
This is also nice
https://github.com/JuliaLang/PackageCompiler.jl

**Comment by guyvdbroeck** [comment]
While trying to address this issue, I ran into https://github.com/timholy/SnoopCompile.jl/issues/237

**Comment by guyvdbroeck** [comment]
I tried using SnoopCompile to generate precompile statements for LogicCircuits, based on the unit tests, and also once based on the readme code. In either case, I was not able to significantly speed up the second-time usage. I could speed up the readme code from 37 to 28 seconds. That does not seem worth the extra overhead of maintaining the precompile files. I'm not sure why precompilation is so ineffective for us.
