### ISSUE TITLE
Retrieve all compiled variables in an SDD manager

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/LogicCircuits.jl#38]
PySDD has a nice API: `a, b, c, d = sdd.vars` for retrieving all the compiled variables in the SDD manager. We currently have to build those variable circuits one by one. We should add this API.

**Comment by khosravipasha** [comment]
@guyvdbroeck  I think we have this now. I guess can close this, unless something else was meant here

for example this from the readme.md
```julia
sun, rain, rainbow, cloud, snow, belgium, los_angeles = pos_literals(Sdd, manager, 7)
```
