### ISSUE TITLE
Julia version requirement for project not satisfied

### ISSUE THREAD

**Issue by michiboo** [Juice-jl/LogicCircuits.jl#41]
Hi I got the following warning when running test:
"julia version requirement for project not satisfied"
while my julia version is version 1.4.2.

I read on doc that prerequisites is Julia 1.3 or greater, so it should be ok.
Any ideas why this happen?

**Comment by YitaoLiang** [comment]
Hi,
  Thanks for reaching out.
  The first thing I would ask, are you using the latest commit in the master branch. Or are you using the released (stable) version?
  If it is the released version, then Julia 1.4 is enough. But if it is the latest commit on the master branch, it actually requires Julia 1.5. Sorry for the confusion. We will try to make this clearer.

**Comment by michiboo** [comment]
@YitaoLiang  Ah ok, thanks for the quick reply!

**Comment by khosravipasha** [comment]
Yes, as Yitao mentioned the lastest commit needs Julia 1.5.  The latest docs are available under "dev": 

https://juice-jl.github.io/LogicCircuits.jl/dev/installation/

We will be releasing version `0.2` soon, in the meanwhile please let us know if you run into any other issues.
