### ISSUE TITLE
Correctness of `isstruct_decomposable` and `infer_vtree`?

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/LogicCircuits.jl#82]
I don't really understand https://github.com/Juice-jl/LogicCircuits.jl/blob/e92c417386f4b3a9089c1302148d30cbe82c6951/src/queries/queries.jl#L154
It is somehow checking locally whether all parent-to-grandparent subcircuits are structured decomposable, but not the entire circuit? I might be misreading the code, but as such I'm not convinced it's correct. If it's correct a little documentation might clarify.

**Comment by khosravipasha** [comment]
Yeah it does not handle all cases correctly. For example, it does not work on non-smooth ones for example #47. Similar thing for `infer_vtree` which I reused parts of `isstruct_decomposable`.

**Comment by guyvdbroeck** [comment]
A fix is to improve `infer_vtree` so that it checks in OR gates whether propagated vtrees are identical and then have `isstruct_decomposable` call `infer_vtree`.

**Comment by khosravipasha** [comment]
Examples from discussion:
```
circuit = (rainbow & sun) | (-rainbow & sun) | (-rainbow & -sun)
isstruct_decomposable(circuit)
```

Also link to equality check for trees https://github.com/Juice-jl/LogicCircuits.jl/blob/27bf8a098a5d08d13a9dd018620c0085382363cd/src/Utils/trees.jl#L34-L40

**Comment by guyvdbroeck** [comment]
It would be good to document somewhere that the code assumes ordered vtrees, and that the AND gates have the right order.
