### ISSUE TITLE
`vtree(root)` returns a circuit node instead of vtree node in some cases

### ISSUE THREAD

**Issue by khosravipasha** [Juice-jl/LogicCircuits.jl#83]
I think it is due to some type issues:
minimal example:

```
using LogicCircuits
random_lc = zoo_sdd("random.sdd");
vtree = zoo_vtree("random.vtree");

plc = propagate_constants(random_lc , remove_unary=true);
structplc = compile(StructLogicCircuit, vtree , plc);
sstructplc = smooth(structplc);

vtree(sstructplc)
```

It returns a `PlainStruct⋁Node` instead of a `PlainVtree`. If I do `sstructplc.vtree` returns the correct value though.

The code seems to be from here, maybe a different code is getting called.
https://github.com/Juice-jl/LogicCircuits.jl/blob/65038f92373d07c58716cfec0d998487a2b8f040/src/structured/structured_logic_nodes.jl#L103

**Comment by talf301** [comment]
I just tinkered with this in console for a bit, I think you're just overwriting the "vtree" name. When I named it vtr instead the vtree() call at the end returns a vtree (I'm not sure what causes that overwrite to have last statement get a circuit type...)

**Comment by khosravipasha** [comment]
oops, yeah, I think you are correct haha. I was expecting the function `vtree` gets called. I think this is common enough (people naming their vtree as vtree) that we should somehow prevent this mistake.

**Comment by guyvdbroeck** [comment]
I removed to ability to use a vtree object as a function to construct circuit nodes in https://github.com/Juice-jl/LogicCircuits.jl/commit/00177e3ad32972c49d6e5e7463e35528510dab70
The code should now throw an error rather than silently giving a circuit node.
